controller_list:
- name: "arm_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

- name: "gripper"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - gripper_finger1_joint
# arm_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gains:
#     shoulder_pan_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     shoulder_lift_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# two_finger_gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - gripper_finger1_joint
#   gains:
#     gripper_finger1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1